ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.chereshniy.HttpKt.configureHttp
      com.chereshniy.MonitoringKt.configureMonitoring
      com.chereshniy.SerializationKt.configureSerialization
      com.chereshniy.SecurityKt.configureSecurity
      com.chereshniy.AutoHeadResponseKt.configureAutoHeadResponse
      com.chereshniy.RequestValidationKt.configureRequestValidation
      com.chereshniy.SseKt.configureSse
      com.chereshniy.StatusPagesKt.configureStatusPages
      com.chereshniy.ExposedKt.configureExposed
      com.chereshniy.RateLimitingKt.configureRateLimiting
      com.chereshniy.WebsocketsKt.configureWebsockets
      com.chereshniy.RoutingKt.configureRouting
    ]
  }
}